### ISSUE TITLE
Add 'install' to Makefile

### ISSUE THREAD

**Issue by JonathonReinhart** [FireyFly/hexd#1]
Same as FireyFly/pixd#3, it'd be great if Makefile had an 'install' option to install the binary, and the man page.

**Comment by FireyFly** [comment]
A couple things here: I'm not sure why, but for some reason this took me forever (and I didn't even leave a comment! sorry!) even though I agree that the Makefile should definitely support `make install`. Either way, I updated the Makefile and now it should support `make install` as one would expect; I also updated it to fix some other things it was lacking while I was at it.

Thanks for opening this issue, and again, sorry for the wait.
